//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ProjetRestauEntities1 : DbContext
{
    public ProjetRestauEntities1()
        : base("name=ProjetRestauEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Applications> Applications { get; set; }
    public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
    public DbSet<Memberships> Memberships { get; set; }
    public DbSet<Profiles> Profiles { get; set; }
    public DbSet<Roles> Roles { get; set; }
    public DbSet<Users> Users { get; set; }
    public DbSet<UsersOpenAuthAccounts> UsersOpenAuthAccounts { get; set; }
    public DbSet<UsersOpenAuthData> UsersOpenAuthData { get; set; }
}
