

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ProjetRestauEntities1 : DbContext
{
    public ProjetRestauEntities1()
        : base("name=ProjetRestauEntities1")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Applications> Applications { get; set; }

    public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public DbSet<Memberships> Memberships { get; set; }

    public DbSet<Profiles> Profiles { get; set; }

    public DbSet<Roles> Roles { get; set; }

    public DbSet<Users> Users { get; set; }

    public DbSet<UsersOpenAuthAccounts> UsersOpenAuthAccounts { get; set; }

    public DbSet<UsersOpenAuthData> UsersOpenAuthData { get; set; }

}

