

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Applications
{

    public Applications()
    {

        this.Memberships = new HashSet<Memberships>();

        this.Roles = new HashSet<Roles>();

        this.Users = new HashSet<Users>();

    }


    public string ApplicationName { get; set; }

    public System.Guid ApplicationId { get; set; }

    public string Description { get; set; }



    public virtual ICollection<Memberships> Memberships { get; set; }

    public virtual ICollection<Roles> Roles { get; set; }

    public virtual ICollection<Users> Users { get; set; }

}


public partial class C__MigrationHistory
{

    public string MigrationId { get; set; }

    public byte[] Model { get; set; }

    public string ProductVersion { get; set; }

}


public partial class Memberships
{

    public System.Guid ApplicationId { get; set; }

    public System.Guid UserId { get; set; }

    public string Password { get; set; }

    public int PasswordFormat { get; set; }

    public string PasswordSalt { get; set; }

    public string Email { get; set; }

    public string PasswordQuestion { get; set; }

    public string PasswordAnswer { get; set; }

    public bool IsApproved { get; set; }

    public bool IsLockedOut { get; set; }

    public System.DateTime CreateDate { get; set; }

    public System.DateTime LastLoginDate { get; set; }

    public System.DateTime LastPasswordChangedDate { get; set; }

    public System.DateTime LastLockoutDate { get; set; }

    public int FailedPasswordAttemptCount { get; set; }

    public System.DateTime FailedPasswordAttemptWindowStart { get; set; }

    public int FailedPasswordAnswerAttemptCount { get; set; }

    public System.DateTime FailedPasswordAnswerAttemptWindowsStart { get; set; }

    public string Comment { get; set; }

    public string adresse { get; set; }



    public virtual Applications Applications { get; set; }

    public virtual Users Users { get; set; }

}


public partial class Profiles
{

    public System.Guid UserId { get; set; }

    public string PropertyNames { get; set; }

    public string PropertyValueStrings { get; set; }

    public byte[] PropertyValueBinary { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }



    public virtual Users Users { get; set; }

}


public partial class Roles
{

    public Roles()
    {

        this.Users = new HashSet<Users>();

    }


    public System.Guid ApplicationId { get; set; }

    public System.Guid RoleId { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }



    public virtual Applications Applications { get; set; }

    public virtual ICollection<Users> Users { get; set; }

}


public partial class Users
{

    public Users()
    {

        this.Roles = new HashSet<Roles>();

    }


    public System.Guid ApplicationId { get; set; }

    public System.Guid UserId { get; set; }

    public string UserName { get; set; }

    public bool IsAnonymous { get; set; }

    public System.DateTime LastActivityDate { get; set; }



    public virtual Applications Applications { get; set; }

    public virtual Memberships Memberships { get; set; }

    public virtual Profiles Profiles { get; set; }

    public virtual ICollection<Roles> Roles { get; set; }

}


public partial class UsersOpenAuthAccounts
{

    public string ApplicationName { get; set; }

    public string ProviderName { get; set; }

    public string ProviderUserId { get; set; }

    public string ProviderUserName { get; set; }

    public string MembershipUserName { get; set; }

    public Nullable<System.DateTime> LastUsedUtc { get; set; }



    public virtual UsersOpenAuthData UsersOpenAuthData { get; set; }

}


public partial class UsersOpenAuthData
{

    public UsersOpenAuthData()
    {

        this.UsersOpenAuthAccounts = new HashSet<UsersOpenAuthAccounts>();

    }


    public string ApplicationName { get; set; }

    public string MembershipUserName { get; set; }

    public bool HasLocalPassword { get; set; }



    public virtual ICollection<UsersOpenAuthAccounts> UsersOpenAuthAccounts { get; set; }

}

